[package]
name = "dotnet-lens"
version = "0.1.0"
edition = "2021"

[dependencies]
serde = { version = "1.0.204", features = ["derive"], optional = true }
spex = "0.2.1"
thiserror = "1.0.63"

[dev-dependencies]
tempfile = "3.10.1"
